### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by Danfro**
Update README.md. I missed the instruction to change into the `axolotl-web` subfolder to run the browser update. The reformatted instructions should make this more obvious.

Update INSTALL.md. 
For one `clickable build --libs` is now called `clickable build-libs`. But when trying this only resulted in errors I dropped it and it still worked. So I think we do not need that line anymore. (?) Am I right?
I also rephrase the instructions to simply use `clickable` as the combined command. The individual commands are given more as a sidenote now.

### CODE REVIEW

**Comment by Danfro** [comment]
I just also improved the notes for translatable strings to include more examples and fix two wrong examples (translatable tag also in "not this way" part).

**Comment by Danfro** [comment]
So we certainly need to amend the instructions further to include comments on how to use the `clickable.yaml` file as discussed in #598 . But I need to know first what to write because there I get the error as described at #598 .

**Comment by Danfro** [comment]
Oh my. I was looking for the build libs instructions and could not find them.

Of course, I already dropped them. So nothing to remove @nanu-c . The part about the build libs was just an explanation. But as I know now, wrong because I did not know that clickable 7 is needed. I will include a note on that into the PR.

**Comment by nanu-c** [comment]
Thank you Danfro!

**Pull request merged**
